name: Persist variables

on:
  workflow_dispatch:
    inputs:
      deploy_acq:
        description: 'Automatically deploy to Acquia staging'
        type: boolean
        default: true
      documentation_access_check:
        description: 'Enable documentation access check for this build'
        type: boolean
        default: false
      enable_company_account_view:
        description: 'Toggle Company Account for the upcoming builds'
        type: boolean
        default: ${{ env.GATSBY_IS_COMPANY_ENABLED }}
jobs:
  persist_variables:
    runs-on: ubuntu-latest
    steps:
    - name: Set output variable
      id: persisted-company
      run: echo "GATSBY_IS_COMPANY_ENABLED=${{ inputs.enable_company_account_view }}" >> $GITHUB_ENV
    - name: Get color
      run: echo "${{ inputs.enable_company_account_view }}"
